spring:
  application:
    name: user-service-ws
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 9091
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'